server:
  port: 3344

spring:
  application:
    name: springcloud-config-server-3344

  #连接远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jin-yuan/MyCode_ForCrawler.git
          username: jin-yuan
          password: shiyu8290
